[package]
name = "hidpipe-shared"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }

[dependencies]
input-linux = { workspace = true }
